import {
  TenantConfig,
  Store,
  Category,
  Product,
  Story,
  Address,
  TenantFeePolicy,
  VisualRule,
  AdminUser,
  AuditLogEntry,
  Order,
  RootCatalogProduct,
  StoreProductAvailability,
  Money,
  toMoney,
  moneyFromMajor,
} from './models';
import {
  MARKET_LANE_STORES,
  MARKET_LANE_CATEGORIES,
  MARKET_LANE_ROOT_PRODUCTS,
  MARKET_LANE_STORE_AVAILABILITY,
} from './marketLaneData';
import { DELIVERECT_3_LEVEL_CATEGORIES } from './deliverectCategories';

export {
  MARKET_LANE_STORES,
  MARKET_LANE_CATEGORIES,
  MARKET_LANE_ROOT_PRODUCTS,
  MARKET_LANE_STORE_AVAILABILITY,
};

export const MOCK_TENANTS: Record<string, TenantConfig> = {
  'brand-alpha': {
    tenantId: 'brand-alpha',
    brandName: 'Chelmsford Artisan Grocer',
    tagline: 'GreenGrocer Express • Fresh essentials in minutes',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=64&auto=format&fit=crop&q=80',
    primaryColour: '#059669', // Emerald Green
    secondaryColour: '#f59e0b', // Amber
    backgroundColour: '#f8fafc',
    textColour: '#0f172a',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    borderRadius: '16px',
    country: 'GB',
    currency: 'GBP',
    currencySymbol: '£',
    locale: 'en-GB',
    supportDetails: {
      email: 'support@brand-alpha.co.uk',
      phone: '0800 123 4567',
      openingHours: 'Mon - Sun: 07:00 - 23:00',
      helpCenterUrl: 'https://help.brand-alpha.co.uk',
    },
    featureFlags: {
      enableStories: true,
      enableRootCatalogBrowse: true,
      enableCollection: true,
      allowStoreSwitchingWithBasket: true,
      enableNutritionalInfo: true,
      enableDeposits: true,
      enableAgeVerification: true,
      enableSearchSuggestions: true,
    },
  },
  'brand-beta': {
    tenantId: 'brand-beta',
    brandName: 'Brand Beta',
    tagline: 'Artisan Pantry & Wine • Curated evening provisions',
    logoUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=200&auto=format&fit=crop&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=64&auto=format&fit=crop&q=80',
    primaryColour: '#4f46e5', // Royal Indigo
    secondaryColour: '#ec4899', // Pink rose
    backgroundColour: '#fdf4ff',
    textColour: '#1e1b4b',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    borderRadius: '12px',
    country: 'GB',
    currency: 'GBP',
    currencySymbol: '£',
    locale: 'en-GB',
    supportDetails: {
      email: 'concierge@brand-beta.co.uk',
      phone: '020 7946 0192',
      openingHours: 'Mon - Sun: 09:00 - 00:00',
      helpCenterUrl: 'https://concierge.brand-beta.co.uk',
    },
    featureFlags: {
      enableStories: true,
      enableRootCatalogBrowse: true,
      enableCollection: true,
      allowStoreSwitchingWithBasket: true,
      enableNutritionalInfo: true,
      enableDeposits: true,
      enableAgeVerification: true,
      enableSearchSuggestions: true,
    },
  },
  'onestop-express': {
    tenantId: 'onestop-express',
    brandName: 'Brand Alpha',
    tagline: 'GreenGrocer Express • Fresh essentials in minutes',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=64&auto=format&fit=crop&q=80',
    primaryColour: '#059669', // Emerald
    secondaryColour: '#f59e0b', // Amber
    backgroundColour: '#f8fafc',
    textColour: '#0f172a',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    borderRadius: '16px',
    country: 'GB',
    currency: 'GBP',
    currencySymbol: '£',
    locale: 'en-GB',
    supportDetails: {
      email: 'support@brand-alpha.co.uk',
      phone: '0800 123 4567',
      openingHours: 'Mon - Sun: 07:00 - 23:00',
      helpCenterUrl: 'https://help.brand-alpha.co.uk',
    },
    featureFlags: {
      enableStories: true,
      enableRootCatalogBrowse: true,
      enableCollection: true,
      allowStoreSwitchingWithBasket: true,
      enableNutritionalInfo: true,
      enableDeposits: true,
      enableAgeVerification: true,
      enableSearchSuggestions: true,
    },
  },
  'greengrocer-co': {
    tenantId: 'greengrocer-co',
    brandName: 'GreenGrocer & Co.',
    tagline: 'Farm-fresh organic groceries to your door',
    logoUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=200&auto=format&fit=crop&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=64&auto=format&fit=crop&q=80',
    primaryColour: '#15803d', // Organic Forest Green
    secondaryColour: '#eab308',
    backgroundColour: '#fafaf9',
    textColour: '#1c1917',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    borderRadius: '20px',
    country: 'GB',
    currency: 'GBP',
    currencySymbol: '£',
    locale: 'en-GB',
    supportDetails: {
      email: 'care@greengrocer.co.uk',
      phone: '0800 987 6543',
      openingHours: 'Everyday 08:00 - 22:00',
    },
    featureFlags: {
      enableStories: true,
      enableRootCatalogBrowse: true,
      enableCollection: true,
      allowStoreSwitchingWithBasket: true,
      enableNutritionalInfo: true,
      enableDeposits: true,
      enableAgeVerification: true,
      enableSearchSuggestions: true,
    },
  },
  'urban-pantry': {
    tenantId: 'urban-pantry',
    brandName: 'Urban Pantry & Wine',
    tagline: 'Curated artisanal deli & evening provisions',
    logoUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=200&auto=format&fit=crop&q=80',
    iconUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=64&auto=format&fit=crop&q=80',
    primaryColour: '#4338ca', // Indigo luxury
    secondaryColour: '#ec4899',
    backgroundColour: '#fdf4ff',
    textColour: '#1e1b4b',
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    borderRadius: '14px',
    country: 'GB',
    currency: 'GBP',
    currencySymbol: '£',
    locale: 'en-GB',
    supportDetails: {
      email: 'concierge@urbanpantry.co.uk',
      phone: '020 7946 0192',
      openingHours: 'Mon - Sun: 09:00 - 00:00',
    },
    featureFlags: {
      enableStories: true,
      enableRootCatalogBrowse: true,
      enableCollection: true,
      allowStoreSwitchingWithBasket: true,
      enableNutritionalInfo: true,
      enableDeposits: true,
      enableAgeVerification: true,
      enableSearchSuggestions: true,
    },
  },
};

export const MOCK_STORES: Store[] = MARKET_LANE_STORES;

export const MOCK_CATEGORIES: Category[] = DELIVERECT_3_LEVEL_CATEGORIES;

export const CORE_REFERENCE_PRODUCTS: RootCatalogProduct[] = [
  {
    id: 'prod-plu-art-001',
    plu: 'PLU-ART-001',
    gtin: ['5051234002018'],
    name: 'Artisan Heritage Sourdough Boule 800g',
    description: 'Slow-fermented regenerative wheat sourdough with blistered mahogany crust and open chewy crumb.',
    brand: 'Wildfarmed Artisan',
    categoryIds: ['cat-bakery', 'cat-bakery-sourdough'],
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80'],
    basePrice: 2.85,
    displayLabels: ['Stonebaked Daily', '36hr Ferment'],
    productTags: ['FRESH', 'ORGANIC', 'VEGAN', 'SPECIAL_OFFER'],
    allergens: ['Wheat (Gluten)'],
    supplementalInfo: {
      netQuantity: '800g',
      storageInstructions: 'Keep in paper bag or bread bin at room temperature',
    },
    deposit: 0,
    active: true,
  },
  {
    id: 'prod-plu-gin-001',
    plu: 'PLU-GIN-001',
    gtin: ['5051234008010'],
    name: 'Cotswolds Artisan Botanical Dry Gin 70cl',
    description: 'Distilled with locally grown Cotswolds lavender, freshly peeled pink grapefruit and lime zest in copper pot stills.',
    brand: 'Cotswolds Distillery',
    categoryIds: ['cat-beer-wine-spirits', 'cat-alcohol-spirits'],
    imageUrl: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1527061011665-3652c757a4d4?w=600&auto=format&fit=crop&q=80'],
    basePrice: 38.00,
    displayLabels: ['18+ Challenge 25', 'Artisan Spirit'],
    productTags: ['ALCOHOL', 'LOCAL'],
    allergens: [],
    deposit: 0,
    active: true,
  },
  {
    id: 'prod-plu-gin-001-70cl',
    plu: 'PLU-GIN-001-70CL',
    gtin: ['5051234008011'],
    name: 'Cotswolds Botanical Dry Gin 70cl (Large)',
    description: 'Large format premium dry gin distilled with lavender and citrus.',
    brand: 'Cotswolds Distillery',
    categoryIds: ['cat-beer-wine-spirits', 'cat-alcohol-spirits'],
    imageUrl: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1527061011665-3652c757a4d4?w=600&auto=format&fit=crop&q=80'],
    basePrice: 38.00,
    displayLabels: ['18+ Challenge 25', 'Large Bottle'],
    productTags: ['ALCOHOL'],
    allergens: [],
    deposit: 0,
    active: true,
  },
  {
    id: 'prod-plu-kom-001',
    plu: 'PLU-KOM-001',
    gtin: ['5051234006030'],
    name: 'Organic Fiery Ginger Kombucha 330ml Can',
    description: 'Raw live sparkling fermented tea cold-infused with organic crushed ginger root and golden turmeric.',
    brand: 'Equinox Kombucha',
    categoryIds: ['cat-drinks', 'cat-drinks-kombucha'],
    imageUrl: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80'],
    basePrice: 2.45,
    displayLabels: ['Raw Live Cultures', '+20p DRS Deposit'],
    productTags: ['ORGANIC', 'VEGAN'],
    allergens: [],
    deposit: 0.20,
    active: true,
  },
  {
    id: 'prod-plu-pepsi-15l',
    plu: 'PLU-PEPSI-15L',
    gtin: ['5000328400018'],
    name: 'Pepsi Max No Sugar Cola 1.5L Bottle',
    description: 'Maximum taste, no sugar cola carbonate beverage.',
    brand: 'Pepsi',
    categoryIds: ['cat-drinks', 'cat-drinks-soda'],
    imageUrl: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600&auto=format&fit=crop&q=80'],
    basePrice: 2.00,
    displayLabels: ['No Sugar', '+20p DRS Deposit'],
    productTags: ['VEGAN'],
    allergens: [],
    deposit: 0.20,
    active: true,
  },
  {
    id: 'prod-plu-pepsi-20l',
    plu: 'PLU-PEPSI-20L',
    gtin: ['5000328400025'],
    name: 'Pepsi Max No Sugar Cola 2L Large Bottle',
    description: 'Large 2L bottle of Pepsi Max No Sugar.',
    brand: 'Pepsi',
    categoryIds: ['cat-drinks', 'cat-drinks-soda'],
    imageUrl: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600&auto=format&fit=crop&q=80'],
    basePrice: 2.40,
    displayLabels: ['No Sugar', 'Price Match'],
    productTags: ['VEGAN'],
    allergens: [],
    deposit: 0.20,
    active: true,
  },
  {
    id: 'prod-plu-bananas-6pk',
    plu: 'PLU-BANANAS-6PK',
    gtin: ['5051234001011'],
    name: 'Fairtrade Organic Bananas 6 Pack',
    description: 'Sustainably sourced, sweet and creamy organic bananas from certified Fairtrade cooperatives in Colombia.',
    brand: 'Market Lane Organics',
    categoryIds: ['cat-fresh-produce', 'cat-fruit-tropical'],
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80'],
    basePrice: 1.50,
    displayLabels: ['Organic', 'Fairtrade'],
    productTags: ['FRESH', 'ORGANIC', 'VEGAN'],
    allergens: [],
    deposit: 0,
    active: true,
  },
  {
    id: 'prod-plu-icecream-vanilla',
    plu: 'PLU-ICECREAM-VANILLA',
    gtin: ['5051234007013'],
    name: 'Madagascan Vanilla Bean Clotted Cream Ice Cream 500ml',
    description: 'Rich artisan clotted cream ice cream infused with real Madagascan Bourbon vanilla seeds.',
    brand: 'Essex Dairy Co.',
    categoryIds: ['cat-dairy-eggs', 'cat-frozen'],
    imageUrl: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&auto=format&fit=crop&q=80'],
    basePrice: 4.50,
    displayLabels: ['Artisan Dairy', 'Local Farm'],
    productTags: ['FRESH', 'VEGETARIAN', 'HFSS'],
    allergens: ['Milk'],
    deposit: 0,
    active: true,
  },
];

const ALL_ROOT_PRODUCTS: RootCatalogProduct[] = [
  ...CORE_REFERENCE_PRODUCTS,
  ...MARKET_LANE_ROOT_PRODUCTS,
];

export const MOCK_PRODUCTS: Product[] = ALL_ROOT_PRODUCTS.map((root) => ({
  id: root.id,
  plu: root.plu,
  gtin: root.gtin,
  name: root.name,
  description: root.description,
  brand: root.brand,
  categoryIds: root.categoryIds,
  imageUrl: root.imageUrl,
  images: root.images,
  price: root.basePrice,
  displayLabels: root.displayLabels,
  productTags: root.productTags,
  allergens: root.allergens,
  nutritionalInfo: root.nutritionalInfo,
  supplementalInfo: root.supplementalInfo,
  beverageInfo: root.beverageInfo,
  deposit: root.deposit,
  multiMax: root.multiMax,
  active: root.active,
  stockStatus: 'IN_STOCK',
  stockQuantity: 40,
}));

// Realistic Instagram-style stories with multiple linked products and AND / OR stock matching rules
export const MOCK_STORIES: Story[] = [
  {
    id: 'story-video-pizza-sizzle',
    title: 'Hot Pizza Sizzle',
    caption: 'Watch the mozzarella bubble! Woodfired sourdough pizzas baked fresh to order in 90 seconds.',
    mediaType: 'video',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    countryCodes: ['GB'],
    storeIds: [],
    action: {
      type: 'PRODUCT',
      targetPlu: 'PLU-PIZZA-MARGHERITA-WOODFIRED',
      buttonLabel: 'Order Fresh Pizza • £5.95',
    },
    tag: 'Live Kitchen 🎥',
    linkedProductPlus: [
      'PLU-PIZZA-MARGHERITA-WOODFIRED',
      'PLU-PIZZA-SPICY-NDUJA-WOODFIRED',
    ],
    stockMatchMode: 'OR',
  },
  {
    id: 'story-meal-deal',
    title: 'Artisan Meal Deal',
    caption: 'Woodfired sourdough pizza, hand-cooked crisps & cold craft beer. All 3 items in stock guarantee.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1080&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=200&auto=format&fit=crop&q=80',
    countryCodes: ['GB'],
    storeIds: [], // Empty storeIds = eligible at all stores where linked stock is available
    action: {
      type: 'PRODUCT',
      targetPlu: 'PLU-PIZZA-MARGHERITA-WOODFIRED',
      buttonLabel: 'Order Meal Deal • £9.95',
    },
    tag: 'Meal Deal (AND)',
    linkedProductPlus: [
      'PLU-PIZZA-MARGHERITA-WOODFIRED',
      'PLU-CRISPS-SEA-SALT-CIDER-150G',
      'PLU-BEER-VERDANT-LIGHTBULB-440ML',
    ],
    stockMatchMode: 'AND', // All 3 components MUST be in stock at the store
  },
  {
    id: 'story-video-cocktail-craft',
    title: 'Cold Drinks & Craft',
    caption: 'Discover cold-chain craft IPAs and organic Chablis, delivered ice cold to your door.',
    mediaType: 'video',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=600&auto=format&fit=crop&q=80',
    countryCodes: ['GB'],
    storeIds: [],
    action: {
      type: 'PRODUCT',
      targetPlu: 'PLU-BEER-VERDANT-LIGHTBULB-440ML',
      buttonLabel: 'Explore Cold Drinks',
    },
    tag: 'Drinks 🎥',
    linkedProductPlus: [
      'PLU-BEER-VERDANT-LIGHTBULB-440ML',
      'PLU-WINE-CHABLIS-ORGANIC-75CL',
    ],
    stockMatchMode: 'OR',
  },
  {
    id: 'story-crisps-snacks',
    title: 'Hand-Cooked Crisps',
    caption: 'Sea Salt & Cider Vinegar or Truffle & Rosemary. Perfect companion for movie night.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=1080&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=200&auto=format&fit=crop&q=80',
    countryCodes: ['GB'],
    storeIds: [], // Links to any location where at least 1 crisp flavour is in stock
    action: {
      type: 'PRODUCT',
      targetPlu: 'PLU-CRISPS-SEA-SALT-CIDER-150G',
      buttonLabel: 'Snack Range • From £1.80',
    },
    tag: 'Snacks (OR)',
    linkedProductPlus: [
      'PLU-CRISPS-SEA-SALT-CIDER-150G',
      'PLU-CRISPS-TRUFFLE-ROSEMARY-150G',
    ],
    stockMatchMode: 'OR', // Shows if AT LEAST 1 flavour is in stock at the store
  },
  {
    id: 'story-pizza-night',
    title: 'Friday Fakeaway',
    caption: 'Woodfired sourdough Margherita & spicy Nduja, hot to your sofa in 20 mins. Tap to shop!',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1080&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=200&auto=format&fit=crop&q=80',
    countryCodes: ['GB'],
    storeIds: [],
    action: {
      type: 'PRODUCT',
      targetPlu: 'PLU-PIZZA-MARGHERITA-WOODFIRED',
      buttonLabel: 'Order Pizza • £5.95',
    },
    tag: 'Trending',
    linkedProductPlus: [
      'PLU-PIZZA-MARGHERITA-WOODFIRED',
      'PLU-PIZZA-SPICY-NDUJA-WOODFIRED',
    ],
    stockMatchMode: 'OR',
  },
  {
    id: 'story-fresh-berries',
    title: 'Berry Harvest',
    caption: 'Fresh British strawberries and raspberries, fragrant and sweet. Hand-selected today.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=1080&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=200&auto=format&fit=crop&q=80',
    countryCodes: ['GB'],
    storeIds: [],
    action: {
      type: 'PRODUCT',
      targetPlu: 'PLU-STRAWBERRY-400G',
      buttonLabel: 'Grab Berries • £2.50',
    },
    tag: 'Local Produce',
    linkedProductPlus: ['PLU-STRAWBERRY-400G', 'PLU-RASPBERRY-150G'],
    stockMatchMode: 'OR',
  },
  {
    id: 'story-wine-pairing',
    title: 'Chilled Rosé & Chablis',
    caption: 'Organic Chablis and crisp Rioja Reserva. Temperature-controlled cellar selection.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=1080&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=200&auto=format&fit=crop&q=80',
    countryCodes: ['GB'],
    storeIds: [],
    action: {
      type: 'PRODUCT',
      targetPlu: 'PLU-WINE-CHABLIS-ORGANIC-75CL',
      buttonLabel: 'Explore Cellar Selection',
    },
    tag: '18+ Only',
    linkedProductPlus: ['PLU-WINE-CHABLIS-ORGANIC-75CL', 'PLU-WINE-RIOJA-RESERVA-75CL'],
    stockMatchMode: 'OR',
  },
  {
    id: 'story-fresh-sourdough',
    title: 'Morning Bake',
    caption: 'Stoneground sourdough boules & all-butter croissants warm from the morning bake.',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=1080&auto=format&fit=crop&q=85',
    thumbnailUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=200&auto=format&fit=crop&q=80',
    countryCodes: ['GB'],
    storeIds: [],
    action: {
      type: 'CATEGORY',
      targetCategoryId: 'cat-fresh-bakery',
      buttonLabel: 'Explore Bakery',
    },
    tag: 'Artisan Bakery',
    linkedProductPlus: ['PLU-SOURDOUGH-BOULE-800G', 'PLU-CROISSANT-ALL-BUTTER-2PK'],
    stockMatchMode: 'OR',
  },
];

export const MOCK_SAVED_ADDRESSES: Address[] = [
  {
    line1: '10 Parkway Gardens',
    city: 'Chelmsford',
    postalCode: 'CM2 0NN',
    country: 'GB',
    formattedAddress: '10 Parkway Gardens, Chelmsford CM2 0NN',
  },
  {
    line1: 'Flat 4, Victoria Court, Duke Street',
    city: 'Chelmsford',
    postalCode: 'CM1 1HT',
    country: 'GB',
    formattedAddress: 'Flat 4, Victoria Court, Duke Street, Chelmsford CM1 1HT',
  },
  {
    line1: '28 Highwood Close',
    city: 'Billericay',
    postalCode: 'CM12 0PX',
    country: 'GB',
    formattedAddress: '28 Highwood Close, Billericay CM12 0PX',
  },
];

export const MOCK_FEE_POLICIES: Record<string, TenantFeePolicy> = {
  'brand-alpha': {
    deliveryFeeMode: 'FIXED',
    fixedDeliveryFee: 1.99,
    dispatchFixedSurcharge: 0.50,
    serviceFeeMode: 'FIXED',
    serviceFeeAmount: 0.49,
    serviceFeeMinCap: 0.49,
    serviceFeeMaxCap: 1.99,
    bagFee: 0.30,
    freeDeliveryThreshold: 35.0,
    minimumBasketThreshold: 10.0,
    smallOrderFee: 1.50,
  },
  'brand-beta': {
    deliveryFeeMode: 'FIXED',
    fixedDeliveryFee: 2.99,
    serviceFeeMode: 'PERCENT',
    serviceFeeAmount: 3.5, // 3.5%
    serviceFeeMinCap: 0.99,
    serviceFeeMaxCap: 3.50,
    bagFee: 0.50,
    freeDeliveryThreshold: 50.0,
    minimumBasketThreshold: 15.0,
    smallOrderFee: 2.00,
  },
  'onestop-express': {
    deliveryFeeMode: 'DISPATCH_PLUS_FIXED',
    fixedDeliveryFee: 1.99,
    dispatchFixedSurcharge: 0.50,
    serviceFeeMode: 'FIXED',
    serviceFeeAmount: 0.49,
    bagFee: 0.35,
    freeDeliveryThreshold: 35.0,
    minimumBasketThreshold: 10.0,
    smallOrderFee: 1.50,
  },
};

export const MOCK_VISUAL_RULES: VisualRule[] = [
  {
    id: 'rule-age-18-alcohol',
    name: 'Alcoholic Beverages Age Restriction (18+)',
    enabled: true,
    countries: ['GB'],
    priority: 100,
    matchConditions: [
      { field: 'productTag', operator: 'equals', value: 'AGE_RESTRICTED_18' },
    ],
    actions: [
      { type: 'MINIMUM_AGE', minimumAge: 18, requiresGate: true, requiresAcknowledgement: true, params: { age: 18 } },
      { type: 'REQUIRES_COURIER_VERIFICATION' },
      { type: 'BADGE', label: '18+ Challenge 25', params: { text: '18+ Challenge 25', color: 'red' } },
    ],
  },
  {
    id: 'rule-medicine-max',
    name: 'Over-the-Counter Medicine Limit',
    enabled: true,
    countries: ['GB'],
    priority: 90,
    matchConditions: [
      { field: 'productTag', operator: 'equals', value: 'MEDICINE_LIMIT' },
    ],
    actions: [
      { type: 'MAX_QUANTITY_PER_ORDER', maximum: 2, params: { max: 2 } },
      { type: 'COMBINED_GROUP_LIMIT', groupId: 'OTC_ANALGESICS', maximum: 2, groupName: 'Pain Relief (OTC)', params: { group: 'OTC_ANALGESICS', max: 2 } },
      { type: 'PREVENT_UPSELL' },
      { type: 'BADGE', label: 'Max 2 per order (MHRA)', params: { text: 'Max 2 per order (MHRA)', color: 'amber' } },
    ],
  },
  {
    id: 'rule-hfss-upsell',
    name: 'HFSS Food Placement & Upsell Restrictions',
    enabled: true,
    countries: ['GB'],
    priority: 80,
    matchConditions: [
      { field: 'productTag', operator: 'equals', value: 'HFSS' },
    ],
    actions: [
      { type: 'PREVENT_UPSELL' },
    ],
  },
];

export const MOCK_ADMIN_USERS: Record<string, AdminUser[]> = {
  'brand-alpha': [
    {
      id: 'usr-alpha-super',
      name: 'Sarah Chen',
      email: 'sarah.chen@platform.internal',
      role: 'platformSuperAdmin',
      tenantId: 'brand-alpha',
    },
    {
      id: 'usr-alpha-owner',
      name: 'Marcus Bell',
      email: 'marcus@brand-alpha.co.uk',
      role: 'tenantAdmin',
      tenantId: 'brand-alpha',
    },
    {
      id: 'usr-alpha-mkt',
      name: 'Elena Rostova',
      email: 'elena.marketing@brand-alpha.co.uk',
      role: 'marketingEditor',
      tenantId: 'brand-alpha',
    },
    {
      id: 'usr-alpha-ops',
      name: 'David Okafor',
      email: 'david.ops@brand-alpha.co.uk',
      role: 'operationsEditor',
      tenantId: 'brand-alpha',
    },
    {
      id: 'usr-alpha-view',
      name: 'Tom Jenkins',
      email: 'tom.viewer@brand-alpha.co.uk',
      role: 'viewer',
      tenantId: 'brand-alpha',
    },
  ],
  'brand-beta': [
    {
      id: 'usr-beta-admin',
      name: 'Julian Montgomery',
      email: 'julian@brand-beta.co.uk',
      role: 'tenantAdmin',
      tenantId: 'brand-beta',
    },
    {
      id: 'usr-beta-mkt',
      name: 'Claire Dupont',
      email: 'claire@brand-beta.co.uk',
      role: 'marketingEditor',
      tenantId: 'brand-beta',
    },
  ],
};

export const ALL_MOCK_ADMIN_USERS: AdminUser[] = Object.values(MOCK_ADMIN_USERS).flat();

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit-001',
    timestamp: '2026-09-16T19:30:00.000Z',
    userId: 'usr-alpha-owner',
    userName: 'Marcus Bell',
    userRole: 'tenantAdmin',
    tenantId: 'brand-alpha',
    category: 'Fees',
    action: 'UPDATE_FEE_POLICY',
    details: 'Changed free delivery threshold from £40.00 to £35.00 and bag fee to £0.35',
  },
  {
    id: 'audit-002',
    timestamp: '2026-09-15T14:12:00.000Z',
    userId: 'usr-alpha-mkt',
    userName: 'Elena Rostova',
    userRole: 'marketingEditor',
    tenantId: 'brand-alpha',
    category: 'Stories',
    action: 'CREATE_STORY',
    details: 'Created story "Essex Organic Strawberries" targeting Chelmsford stores',
  },
  {
    id: 'audit-003',
    timestamp: '2026-09-14T10:05:00.000Z',
    userId: 'usr-alpha-owner',
    userName: 'Marcus Bell',
    userRole: 'tenantAdmin',
    tenantId: 'brand-alpha',
    category: 'Branding',
    action: 'UPDATE_BRANDING',
    details: 'Updated primary theme colour to #059669 (Emerald) and border radius to 16px',
  },
  {
    id: 'audit-004',
    timestamp: '2026-09-13T08:45:00.000Z',
    userId: 'usr-alpha-super',
    userName: 'Sarah Chen',
    userRole: 'platformSuperAdmin',
    tenantId: 'brand-alpha',
    category: 'Rules',
    action: 'SYNC_MHRA_MEDICINE_RULE',
    details: 'Enforced maximum 2 packs combined limit across OTC analgesics',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-alpha-991204',
    displayId: '#ORD-991204',
    orderReference: 'ORD-991204',
    tenantId: 'brand-alpha',
    storeId: 'store-chelmsford-central',
    storeName: 'Chelmsford High St Express',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 80500000).toISOString(),
    status: 'delivered',
    statusHistory: [
      { status: 'orderAccepted', timestamp: new Date(Date.now() - 86400000).toISOString() },
      { status: 'preparing', timestamp: new Date(Date.now() - 85200000).toISOString() },
      { status: 'readyForPickup', timestamp: new Date(Date.now() - 84000000).toISOString() },
      { status: 'courierAssigned', timestamp: new Date(Date.now() - 83500000).toISOString() },
      { status: 'courierAtStore', timestamp: new Date(Date.now() - 82800000).toISOString() },
      { status: 'outForDelivery', timestamp: new Date(Date.now() - 82000000).toISOString() },
      { status: 'delivered', timestamp: new Date(Date.now() - 80500000).toISOString() },
    ],
    fulfillment: {
      type: 'delivery',
      address: {
        line1: '10 Parkway Gardens',
        city: 'Chelmsford',
        postalCode: 'CM2 0NN',
        country: 'GB',
        formattedAddress: '10 Parkway Gardens, Chelmsford CM2 0NN',
      },
      schedulingMode: 'RESERVE_AT_ORDER',
    },
    scheduledTime: {
      type: 'ASAP',
      asapEtaMinutes: 25,
      requestedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    originalBasket: {
      id: 'bsk-hist-01',
      storeId: 'store-chelmsford-central',
      storeName: 'Chelmsford High St Express',
      fulfillmentType: 'delivery',
      items: [
        { id: 'i1', plu: 'PLU-STRAWBERRY-400G', name: 'Essex Fresh Strawberries 400g', price: moneyFromMajor(2.85), unitPrice: moneyFromMajor(2.85), totalPrice: moneyFromMajor(5.70), quantity: 2 },
        { id: 'i2', plu: 'PLU-SOURDOUGH-01', name: 'Artisan Country Sourdough 800g', price: moneyFromMajor(3.40), unitPrice: moneyFromMajor(3.40), totalPrice: moneyFromMajor(3.40), quantity: 1 },
      ],
      subtotal: moneyFromMajor(9.10),
      discounts: [],
      discountTotal: toMoney(0, 'GBP'),
      charges: [
        { id: 'c1', type: 'deliveryFee', title: 'Courier Delivery', amount: moneyFromMajor(1.99) },
        { id: 'c2', type: 'serviceCharge', title: 'Service Fee', amount: moneyFromMajor(0.49) },
        { id: 'c3', type: 'bagFee', title: 'Recyclable Bag', amount: moneyFromMajor(0.35) },
      ],
      total: moneyFromMajor(11.93),
      currency: 'GBP',
      validationErrors: [],
      restrictions: [],
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    currentOrder: {
      subtotal: moneyFromMajor(9.10),
      charges: [
        { id: 'c1', type: 'deliveryFee', title: 'Courier Delivery', amount: moneyFromMajor(1.99) },
        { id: 'c2', type: 'serviceCharge', title: 'Service Fee', amount: moneyFromMajor(0.49) },
        { id: 'c3', type: 'bagFee', title: 'Recyclable Bag', amount: moneyFromMajor(0.35) },
      ],
      discounts: [],
      depositTotal: toMoney(0, 'GBP'),
      bagFee: moneyFromMajor(0.35),
      serviceCharge: moneyFromMajor(0.49),
      deliveryCharge: moneyFromMajor(1.99),
      tip: toMoney(0, 'GBP'),
      total: moneyFromMajor(11.93),
      itemCount: 3,
    },
    payment: {
      paymentId: 'pay_hist_01',
      state: 'CAPTURED',
      currency: 'GBP',
      authorizedAmount: moneyFromMajor(11.93),
      authorizationMaximum: moneyFromMajor(13.00),
      finalAmount: moneyFromMajor(11.93),
      capturedAmount: moneyFromMajor(11.93),
      method: 'Deliverect Pay (Apple Pay)',
      history: [
        { state: 'AUTHORIZED', timestamp: new Date(Date.now() - 86400000).toISOString(), amount: moneyFromMajor(13.00) },
        { state: 'CAPTURED', timestamp: new Date(Date.now() - 84000000).toISOString(), amount: moneyFromMajor(11.93) },
      ],
    },
    picking: {
      status: 'COMPLETED',
      totalItems: 2,
      itemsPicked: 2,
      hasChanges: false,
      items: [
        {
          id: 'pi-1',
          plu: 'PLU-STRAWBERRY-400G',
          name: 'Essex Fresh Strawberries 400g',
          originalQuantity: 2,
          pickedQuantity: 2,
          originalPrice: moneyFromMajor(5.70),
          finalPrice: moneyFromMajor(5.70),
          state: 'PICKED',
        },
        {
          id: 'pi-2',
          plu: 'PLU-SOURDOUGH-01',
          name: 'Artisan Country Sourdough 800g',
          originalQuantity: 1,
          pickedQuantity: 1,
          originalPrice: moneyFromMajor(3.40),
          finalPrice: moneyFromMajor(3.40),
          state: 'PICKED',
        },
      ],
    },
    events: [
      { id: 'ev-1', status: 'delivered', title: 'Order Delivered', timestamp: new Date(Date.now() - 80500000).toISOString() },
    ],
    basket: {
      id: 'bsk-hist-01',
      storeId: 'store-chelmsford-central',
      storeName: 'Chelmsford High St Express',
      fulfillmentType: 'delivery',
      items: [
        { id: 'i1', plu: 'PLU-STRAWBERRY-400G', name: 'Essex Fresh Strawberries 400g', price: moneyFromMajor(2.85), unitPrice: moneyFromMajor(2.85), totalPrice: moneyFromMajor(5.70), quantity: 2 },
        { id: 'i2', plu: 'PLU-SOURDOUGH-01', name: 'Artisan Country Sourdough 800g', price: moneyFromMajor(3.40), unitPrice: moneyFromMajor(3.40), totalPrice: moneyFromMajor(3.40), quantity: 1 },
      ],
      subtotal: moneyFromMajor(9.10),
      discounts: [],
      discountTotal: toMoney(0, 'GBP'),
      charges: [
        { id: 'c1', type: 'deliveryFee', title: 'Courier Delivery', amount: moneyFromMajor(1.99) },
        { id: 'c2', type: 'serviceCharge', title: 'Service Fee', amount: moneyFromMajor(0.49) },
        { id: 'c3', type: 'bagFee', title: 'Recyclable Bag', amount: moneyFromMajor(0.35) },
      ],
      total: moneyFromMajor(11.93),
      currency: 'GBP',
      validationErrors: [],
      restrictions: [],
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    deliveryAddress: {
      line1: '10 Parkway Gardens',
      city: 'Chelmsford',
      postalCode: 'CM2 0NN',
      country: 'GB',
      formattedAddress: '10 Parkway Gardens, Chelmsford CM2 0NN',
    },
    courier: {
      name: 'Kev M.',
      phone: '07700 900123',
      vehicleType: 'E-Cargo Bike',
      eta: 'Delivered',
    },
    paymentSummary: {
      method: 'Deliverect Pay (Apple Pay)',
      totalPaid: 11.93,
      transactionRef: 'txn_dp_991204_live',
      currency: 'GBP',
    },
  },
];

